Avoid toString() for converting integer types to BigInteger and BigDecimal
apache/groovy pull request #1437
Opened 2020-11-30 13:08 UTC by moonfruit

Avoid toString() for converting integer types to BigInteger and BigDecimal.

2020-11-30 13:34 UTC, danielsun1106 requested changes

2020-11-30 13:34 UTC, danielsun1106 commented on src/main/java/org/codehaus/groovy/runtime/typehandling/NumberMath.java
> +        if (n instanceof Byte || n instanceof Short || n instanceof Integer || n instanceof Long) {
I suggest to put Integer and Long at the beginning to avoid checks as possible as we could, because we use Integer and Long more often in the life 😉

2020-11-30 13:34 UTC, danielsun1106 commented on src/main/java/org/codehaus/groovy/runtime/typehandling/NumberMath.java
> +        if (n instanceof Byte || n instanceof Short || n instanceof Integer || n instanceof Long) {
Ditto

2020-11-30 14:15 UTC, closed without merging

2020-11-30 14:18 UTC, danielsun1106 commented
Merged. Thanks!

2020-12-01 03:31 UTC, moonfruit commented
@danielsun1106 Should I move Integer and Long to the beginning of the conditions?

2020-12-01 04:01 UTC, danielsun1106 commented
Your PR has been merged :-)
https://github.com/apache/groovy/commit/8af30255c45d9adb6f80590d6ca13885d1b338d7

and I've tweaked it to catch the release train:
https://github.com/apache/groovy/commit/dab8f4e1f277701948db1e56d19ee1ecb8861051

2020-12-01 04:41 UTC, moonfruit commented
Thank you!

2020-12-01 07:26 UTC, moonfruit commented
@danielsun1106 For 6f08fd0, convert from `BigDecimal` to `BigInteger`, better use `((BigDecimal) n).toBigIntegerExact()` instead of `new BigInteger(((BigDecimal) n).toPlainString())`.

Should I make another pull request?

2020-12-01 08:06 UTC, danielsun1106 commented
@moonfruit Nice catch. New PR is welcome ;-)